name: Create Stark Extensions CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Setup Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack and set Yarn version
        run: |
          corepack enable
          yarn set version 3.5.0

      - name: Checkout Create Stark Repository
        uses: actions/checkout@v4
        with:
          repository: Scaffold-Stark/create-stark
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          path: create-stark

      - name: Install dependencies (Create Stark)
        run: yarn install --immutable
        working-directory: ./create-stark

      - name: Modify create-stark to use local extensions
        shell: bash
        run: |
          set -euo pipefail
          echo "Current branch: $BRANCH_NAME"
          EXT_FILE=./create-stark/src/extensions.json
          if ! command -v jq >/dev/null 2>&1; then
            echo "jq not found. Installing..."
            sudo apt-get update -y && sudo apt-get install -y jq
          fi
          tmp_file=$(mktemp)
          jq --arg bn "$BRANCH_NAME" \
            '.[. | length] = {
              "extensionFlagValue": $bn,
              "description": ("CI to test " + $bn),
              "repository": "https://github.com/Scaffold-Stark/create-starknet-extensions",
              "branch": $bn
            }' "$EXT_FILE" > "$tmp_file"
          mv "$tmp_file" "$EXT_FILE"
          cat "$EXT_FILE"

      - name: Build Create Stark CLI
        run: yarn build
        working-directory: ./create-stark

      - name: Scaffold test project using current branch extension
        run: |
          yarn cli -e "$BRANCH_NAME" -d test-project -i
        working-directory: ./create-stark

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./create-stark/test-project/.tool-versions

      - name: Install snfoundryup
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./create-stark/test-project/.tool-versions

      - name: Deploy contracts
        run: yarn deploy
        working-directory: ./create-stark/test-project

      - name: Run smart contract tests
        run: yarn test
        working-directory: ./create-stark/test-project

      - name: Check Code Format
        run: yarn format:check
        working-directory: ./create-stark/test-project

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./create-stark/test-project/packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./create-stark/test-project/packages/nextjs

      - name: Run Next.js tests
        run: yarn test
        working-directory: ./create-stark/test-project/packages/nextjs

      - name: Build Next.js project
        run: yarn build
        working-directory: ./create-stark/test-project/packages/nextjs
